cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(sampler C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()

add_executable(sampler sampler.c)
pico_generate_pio_header(sampler ${CMAKE_CURRENT_LIST_DIR}/sampler.pio)
pico_enable_stdio_usb(sampler 1)
pico_enable_stdio_uart(sampler 1)
target_link_libraries(sampler pico_stdlib hardware_pio hardware_dma hardware_clocks)
pico_add_extra_outputs(sampler)
